spring.application.name=Banking-Mangment

#DB configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_management
spring.datasource.username=postgres
spring.datasource.password=0000


server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#security config
#spring.security.user.name=nishu
#spring.security.user.password=pass

# JWT Configuration
jwt.secret=8d7f6c5b4a3928173645546372819abcdef1234567890abcdef1234567890ab
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE
server.error.include-message=always
server.error.include-stacktrace=always